name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Test in Dev Container
              uses: devcontainers/ci@v0.2
              with:
                  push: never
                  runCmd: pnpm test
